#!/bin/bash
#
# Sample startup script for FreeNX server
#

# Read the config file
. $(PATH=$(cd $(dirname $0) && pwd):$PATH which nxloadconfig) --

case "$1" in
	start)
		[ ! -d "/tmp/.X11-unix" ] && mkdir -m1755 /tmp/.X11-unix/
		$PATH_BIN/nxserver --cleanup
	;;
	stop)
		$PATH_BIN/nxserver --cleanup
	;;	
	*)
		echo "Usage: $0 <start|stop>"
	;;
esac
