#!/bin/sh

[ -f "$NX_ROOT/cups/cupsd.pid" ] && CPID=$(cat "$NX_ROOT/cups/cupsd.pid")

[ -n "$CPID" ] && kill -0 $CPID && kill $CPID

echo "PidFile $NX_ROOT/cups/cupsd.pid" >> $NX_ROOT/cups/cupsd.conf
echo "StateDir $NX_ROOT/cups/" >> $NX_ROOT/cups/cupsd.conf

mkdir -p $NX_HOME/cups/ppd/

for i in $(lpstat -s | cut -d" " -f4)
do
	LD_LIBRARY_PATH="" wget -q ${i/ipp/http}.ppd -O $NX_ROOT/cups/ppd/$(basename $i)_nxdl.ppd
done

exec /usr/sbin/cupsd "$@" 
